CREATE USER pedroars WITH PASSWORD 'jw8s0F4';
CREATE USER MuhammadAdnan WITH PASSWORD 'jw8s0F4';
CREATE USER ShazeemAshar WITH PASSWORD 'jw8s0F4';
CREATE USER ArsalanShahid WITH PASSWORD 'jw8s0F4';
CREATE USER MuteeUrRehman WITH PASSWORD 'jw8s0F4';
CREATE USER keycloak WITH PASSWORD 'jw8s0F4';
CREATE USER production WITH PASSWORD 'jw8s0F4';